---
# tasks file for recover-ocp4

# ansible-playbook -e [ running | stopped ] ./hack_infrastructure_states.yml

- name: Start or Stop A cluster
  hosts: localhost

  tasks:

    - name: get facts of instances with no public DNS
      ec2_instance_facts:
        filters:
          dns-name: ""
      register: ec2
    - debug: var=ec2

    - name: set state of the dns-name "" instances
      ec2:
        instance_ids: "{{ item.instance_id }}"
        state: "{{ state }}"
        region: "us-east-2"
      loop: "{{ ec2.instances }} "

